table ab_test_power_analysis
	lineageTag: d7dd2b11-9da8-43dc-8d84-086bd2c292cb

	column experiment_id
		dataType: string
		lineageTag: 716e1e43-c71b-4903-ba8c-d4c29d2d3beb
		summarizeBy: none
		sourceColumn: experiment_id

		annotation SummarizationSetBy = Automatic

	column primary_metric
		dataType: string
		lineageTag: 6461d283-5b63-4b44-b826-092441405c4e
		summarizeBy: none
		sourceColumn: primary_metric

		annotation SummarizationSetBy = Automatic

	column baseline_success_rate
		dataType: double
		lineageTag: 1d747097-9cf1-4351-b5db-5f578fe35093
		summarizeBy: sum
		sourceColumn: baseline_success_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column baseline_source
		dataType: string
		lineageTag: 712700c1-8594-43d5-86d8-94480e49a685
		summarizeBy: none
		sourceColumn: baseline_source

		annotation SummarizationSetBy = Automatic

	column absolute_lift
		dataType: double
		lineageTag: d42af36d-8c7c-420b-8419-b608a5078171
		summarizeBy: sum
		sourceColumn: absolute_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column relative_mde
		dataType: double
		lineageTag: b0af1aa0-3fe6-4e6c-9f42-a6e3fa29cda5
		summarizeBy: sum
		sourceColumn: relative_mde

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column treatment_success_rate
		dataType: double
		lineageTag: a30fcdef-f861-4068-be20-170e9e3868c4
		summarizeBy: sum
		sourceColumn: treatment_success_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alpha
		dataType: double
		lineageTag: 97b92ae3-c267-4cb0-8646-32f0d52f50ec
		summarizeBy: sum
		sourceColumn: alpha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_power
		dataType: double
		lineageTag: b00fe869-2c67-440f-ac12-f06161ffd4cd
		summarizeBy: sum
		sourceColumn: target_power

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column required_n_per_group
		dataType: int64
		formatString: 0
		lineageTag: cbf8d955-45b0-4763-a48f-b1fbbcffb664
		summarizeBy: sum
		sourceColumn: required_n_per_group

		annotation SummarizationSetBy = Automatic

	column required_total_n
		dataType: int64
		formatString: 0
		lineageTag: 92ef8c85-5124-4462-8f2d-8d9f1bd8596a
		summarizeBy: sum
		sourceColumn: required_total_n

		annotation SummarizationSetBy = Automatic

	column available_n_per_group
		dataType: int64
		formatString: 0
		lineageTag: ad375549-7a0e-4112-9d71-0e559e4d0a8a
		summarizeBy: sum
		sourceColumn: available_n_per_group

		annotation SummarizationSetBy = Automatic

	column available_total_n
		dataType: int64
		formatString: 0
		lineageTag: 8bafe611-b286-4bc5-a136-16a419766964
		summarizeBy: sum
		sourceColumn: available_total_n

		annotation SummarizationSetBy = Automatic

	column available_power
		dataType: double
		lineageTag: 2e706abc-fe8f-407c-92da-8420bc04dd81
		summarizeBy: sum
		sourceColumn: available_power

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minimum_detectable_effect
		dataType: double
		lineageTag: e308d90d-83c3-40c1-ab92-d4cd8dfc2f77
		summarizeBy: sum
		sourceColumn: minimum_detectable_effect

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column feasible_with_current_sample
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c21d885c-62ca-4b6e-812d-4a77b4521c10
		summarizeBy: none
		sourceColumn: feasible_with_current_sample

		annotation SummarizationSetBy = Automatic

	partition ab_test_power_analysis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_power_analysis.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"experiment_id", type text}, {"primary_metric", type text}, {"baseline_success_rate", type number}, {"baseline_source", type text}, {"absolute_lift", type number}, {"relative_mde", type number}, {"treatment_success_rate", type number}, {"alpha", type number}, {"target_power", type number}, {"required_n_per_group", Int64.Type}, {"required_total_n", Int64.Type}, {"available_n_per_group", Int64.Type}, {"available_total_n", Int64.Type}, {"available_power", type number}, {"minimum_detectable_effect", type number}, {"feasible_with_current_sample", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

