table ab_test_srm_check
	lineageTag: c23d76bf-3d55-4c72-957e-a1a1d3fe3459

	column experiment_id
		dataType: string
		lineageTag: ccf0c02e-264a-495b-a094-c50ffd7feda9
		summarizeBy: none
		sourceColumn: experiment_id

		annotation SummarizationSetBy = Automatic

	column check_name
		dataType: string
		lineageTag: 23627705-a7a4-4ebd-a477-eb5c3063f87d
		summarizeBy: none
		sourceColumn: check_name

		annotation SummarizationSetBy = Automatic

	column statistical_test
		dataType: string
		lineageTag: 216d65f1-6f8e-4395-8020-5ba8f506169d
		summarizeBy: none
		sourceColumn: statistical_test

		annotation SummarizationSetBy = Automatic

	column expected_control_share
		dataType: double
		lineageTag: 3666cf2a-7ac4-454e-b2cb-8b088e5839c7
		summarizeBy: sum
		sourceColumn: expected_control_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column expected_treatment_share
		dataType: double
		lineageTag: f22bcb5f-c5ac-4d4a-9d09-0550ddf24d93
		summarizeBy: sum
		sourceColumn: expected_treatment_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column observed_control_n
		dataType: int64
		formatString: 0
		lineageTag: 1e5cdb76-00ac-433d-a1f6-cc9dddddae25
		summarizeBy: sum
		sourceColumn: observed_control_n

		annotation SummarizationSetBy = Automatic

	column observed_treatment_n
		dataType: int64
		formatString: 0
		lineageTag: 1ed20a41-ef8f-4b93-b5c8-50d532a638a6
		summarizeBy: sum
		sourceColumn: observed_treatment_n

		annotation SummarizationSetBy = Automatic

	column observed_control_share
		dataType: double
		lineageTag: 72adca8a-fc4b-42f3-bcdc-7cc8fc4d6010
		summarizeBy: sum
		sourceColumn: observed_control_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column observed_treatment_share
		dataType: double
		lineageTag: 8e19191f-cb42-4e8e-9489-c3fe72c5812a
		summarizeBy: sum
		sourceColumn: observed_treatment_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chi_square_statistic
		dataType: double
		lineageTag: d4f3c685-c26a-40fb-babb-6baee57f1c2d
		summarizeBy: sum
		sourceColumn: chi_square_statistic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column p_value
		dataType: double
		lineageTag: ca020c99-2ab9-46f8-9329-06a3aa6701d8
		summarizeBy: sum
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alpha
		dataType: double
		lineageTag: f103c6bb-47ec-4554-b646-0031768d54e1
		summarizeBy: sum
		sourceColumn: alpha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column passed_srm_check
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3b08b6c5-e4f7-4ec8-907f-9d9112bf951d
		summarizeBy: none
		sourceColumn: passed_srm_check

		annotation SummarizationSetBy = Automatic

	column interpretation
		dataType: string
		lineageTag: 5583621c-52dd-4c9e-912a-bf3b645a5671
		summarizeBy: none
		sourceColumn: interpretation

		annotation SummarizationSetBy = Automatic

	partition ab_test_srm_check = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_srm_check.csv"),[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"experiment_id", type text}, {"check_name", type text}, {"statistical_test", type text}, {"expected_control_share", type number}, {"expected_treatment_share", type number}, {"observed_control_n", Int64.Type}, {"observed_treatment_n", Int64.Type}, {"observed_control_share", type number}, {"observed_treatment_share", type number}, {"chi_square_statistic", type number}, {"p_value", type number}, {"alpha", type number}, {"passed_srm_check", type logical}, {"interpretation", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

