table ab_test_experiment_design
	lineageTag: 826fe631-bde0-4da4-a384-62fb463c5695

	column experiment_id
		dataType: string
		lineageTag: e59c7720-0f69-431d-b151-f74b43b3ccdd
		summarizeBy: none
		sourceColumn: experiment_id

		annotation SummarizationSetBy = Automatic

	column design_component
		dataType: string
		lineageTag: b828fed3-4ecc-4476-9dc5-79023dca07b0
		summarizeBy: none
		sourceColumn: design_component

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: e9edc5e4-c91a-4aa1-bef8-5d0ea3c8d945
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column lecture_alignment
		dataType: string
		lineageTag: 4a3696d2-acdd-4eb4-a7ee-8f892811360b
		summarizeBy: none
		sourceColumn: lecture_alignment

		annotation SummarizationSetBy = Automatic

	partition ab_test_experiment_design = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_experiment_design.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"experiment_id", type text}, {"design_component", type text}, {"value", type text}, {"lecture_alignment", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

