table ab_test_assignment
	lineageTag: 2543ee3b-572d-4059-a0dc-d5b52e409958

	column experiment_id
		dataType: string
		lineageTag: e63073a1-f478-4072-91ec-1074fd711941
		summarizeBy: none
		sourceColumn: experiment_id

		annotation SummarizationSetBy = Automatic

	column assignment_unit
		dataType: string
		lineageTag: e52c0439-acef-41dd-a7c7-82b6ab157416
		summarizeBy: none
		sourceColumn: assignment_unit

		annotation SummarizationSetBy = Automatic

	column eligibility_rule
		dataType: string
		lineageTag: 5296d5bd-4912-4d25-bcaa-7203c8ecc26c
		summarizeBy: none
		sourceColumn: eligibility_rule

		annotation SummarizationSetBy = Automatic

	column variant
		dataType: string
		lineageTag: e196f266-c1e4-4c1a-8e20-6c0d242550dd
		summarizeBy: none
		sourceColumn: variant

		annotation SummarizationSetBy = Automatic

	column variant_label
		dataType: string
		lineageTag: 2a9f3f54-5c2a-4dbf-a78f-bfd5c1f9449d
		summarizeBy: none
		sourceColumn: variant_label

		annotation SummarizationSetBy = Automatic

	column primary_metric
		dataType: string
		lineageTag: a68cdf36-6d8d-447f-9bf9-847d8e8cbdea
		summarizeBy: none
		sourceColumn: primary_metric

		annotation SummarizationSetBy = Automatic

	column primary_metric_observed
		dataType: int64
		formatString: 0
		lineageTag: 9bc073ed-3bcf-41d8-93ef-c11da1853c81
		summarizeBy: sum
		sourceColumn: primary_metric_observed

		annotation SummarizationSetBy = Automatic

	column historical_outcome_note
		dataType: string
		lineageTag: 2587ddb6-17ce-4058-bd34-04b66c9d2778
		summarizeBy: none
		sourceColumn: historical_outcome_note

		annotation SummarizationSetBy = Automatic

	column stratification_key
		dataType: string
		lineageTag: 17509c2f-b6e9-4de3-8133-07918c864185
		summarizeBy: none
		sourceColumn: stratification_key

		annotation SummarizationSetBy = Automatic

	column random_state
		dataType: int64
		formatString: 0
		lineageTag: c6ab1d08-eee9-4b63-931d-5da38310b8bf
		summarizeBy: sum
		sourceColumn: random_state

		annotation SummarizationSetBy = Automatic

	column id_student
		dataType: int64
		formatString: 0
		lineageTag: a3765301-b083-4ec2-b751-2f5b7cf986fd
		summarizeBy: sum
		sourceColumn: id_student

		annotation SummarizationSetBy = Automatic

	column code_module
		dataType: string
		lineageTag: 1b582c3e-c285-4a12-aafc-a5996e0e205e
		summarizeBy: none
		sourceColumn: code_module

		annotation SummarizationSetBy = Automatic

	column code_presentation
		dataType: string
		lineageTag: d1d23e0d-d6f6-4a31-a980-dd3fad499a98
		summarizeBy: none
		sourceColumn: code_presentation

		annotation SummarizationSetBy = Automatic

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: 06784890-9fc9-4c52-b3cc-212976209f6f
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 53bccdf5-bb22-4253-b900-86ad74af7c0c
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column selected_threshold
		dataType: double
		lineageTag: 5fcfb1f0-01e0-4d59-a450-cc41f484deb1
		summarizeBy: sum
		sourceColumn: selected_threshold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column y_true
		dataType: int64
		formatString: 0
		lineageTag: efec5b9a-2709-487a-be0f-a03623bbcfd3
		summarizeBy: sum
		sourceColumn: y_true

		annotation SummarizationSetBy = Automatic

	column risk_probability
		dataType: double
		lineageTag: 490f02db-8351-4c63-907b-81635bde2eb7
		summarizeBy: sum
		sourceColumn: risk_probability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column y_pred
		dataType: int64
		formatString: 0
		lineageTag: a2c50f38-1a4d-4be0-b851-21de89221a31
		summarizeBy: sum
		sourceColumn: y_pred

		annotation SummarizationSetBy = Automatic

	column risk_band
		dataType: string
		lineageTag: e0148dd7-46d0-46cc-b92a-384206e5bf5b
		summarizeBy: none
		sourceColumn: risk_band

		annotation SummarizationSetBy = Automatic

	column final_result
		dataType: string
		lineageTag: b4a9f6d9-86cd-48b0-9069-112722324957
		summarizeBy: none
		sourceColumn: final_result

		annotation SummarizationSetBy = Automatic

	column cluster_label
		dataType: string
		lineageTag: 4270bfaf-e22d-4acf-9b0c-691f48a0e21b
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column rule_segment
		dataType: string
		lineageTag: cf37a786-d8ac-4b19-8457-e1036fd60d32
		summarizeBy: none
		sourceColumn: rule_segment

		annotation SummarizationSetBy = Automatic

	column recommended_path
		dataType: string
		lineageTag: e328458a-d451-44f1-8450-c0fa31bdcf6f
		summarizeBy: none
		sourceColumn: recommended_path

		annotation SummarizationSetBy = Automatic

	column action_1
		dataType: string
		lineageTag: 28409545-b5d3-460a-8cd9-30ae28283ca2
		summarizeBy: none
		sourceColumn: action_1

		annotation SummarizationSetBy = Automatic

	column action_2
		dataType: string
		lineageTag: ce910618-e8f7-433a-bdf6-b3ed974fa3a5
		summarizeBy: none
		sourceColumn: action_2

		annotation SummarizationSetBy = Automatic

	column action_3
		dataType: string
		lineageTag: 28b00587-f6e4-4c02-8603-cd3023d74c4c
		summarizeBy: none
		sourceColumn: action_3

		annotation SummarizationSetBy = Automatic

	column recommendation_score
		dataType: double
		lineageTag: 8c501fad-2640-43ae-ad28-730babc5dedb
		summarizeBy: sum
		sourceColumn: recommendation_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_outcome
		dataType: string
		lineageTag: 0b75c6ba-8067-4208-81af-c52933c69bd5
		summarizeBy: none
		sourceColumn: prediction_outcome

		annotation SummarizationSetBy = Automatic

	column risk_band_method
		dataType: string
		lineageTag: 677fac06-f490-4e60-990c-b4eb1fabde06
		summarizeBy: none
		sourceColumn: risk_band_method

		annotation SummarizationSetBy = Automatic

	column EnrollmentKey
		dataType: string
		lineageTag: 54bcdbff-2758-425b-b37b-003955810481
		summarizeBy: none
		sourceColumn: EnrollmentKey

		annotation SummarizationSetBy = Automatic

	partition ab_test_assignment = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_assignment.csv"),[Delimiter=",", Columns=30, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"experiment_id", type text}, {"assignment_unit", type text}, {"eligibility_rule", type text}, {"variant", type text}, {"variant_label", type text}, {"primary_metric", type text}, {"primary_metric_observed", Int64.Type}, {"historical_outcome_note", type text}, {"stratification_key", type text}, {"random_state", Int64.Type}, {"id_student", Int64.Type}, {"code_module", type text}, {"code_presentation", type text}, {"horizon_day", Int64.Type}, {"model", type text}, {"selected_threshold", type number}, {"y_true", Int64.Type}, {"risk_probability", type number}, {"y_pred", Int64.Type}, {"risk_band", type text}, {"final_result", type text}, {"cluster_label", type text}, {"rule_segment", type text}, {"recommended_path", type text}, {"action_1", type text}, {"action_2", type text}, {"action_3", type text}, {"recommendation_score", type number}, {"prediction_outcome", type text}, {"risk_band_method", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "EnrollmentKey", each Text.From([id_student]) & "|" & [code_module] & "|" & [code_presentation]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"EnrollmentKey", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

