table ab_test_simulated_results
	lineageTag: 3d5cec9c-8cb4-4cef-bd46-1100ad7d7b80

	column experiment_id
		dataType: string
		lineageTag: 94005885-8ca9-428c-a724-80201590e196
		summarizeBy: none
		sourceColumn: experiment_id

		annotation SummarizationSetBy = Automatic

	column scenario
		dataType: string
		lineageTag: 786f4163-8d5b-4dd7-83fe-f7fd7ab1e9a1
		summarizeBy: none
		sourceColumn: scenario

		annotation SummarizationSetBy = Automatic

	column scenario_type
		dataType: string
		lineageTag: 1c3393a5-1e34-4d15-88f1-3a48e7667696
		summarizeBy: none
		sourceColumn: scenario_type

		annotation SummarizationSetBy = Automatic

	column n_control
		dataType: int64
		formatString: 0
		lineageTag: 922d609c-ca27-450f-8434-f07b397b9ef4
		summarizeBy: sum
		sourceColumn: n_control

		annotation SummarizationSetBy = Automatic

	column n_treatment
		dataType: int64
		formatString: 0
		lineageTag: 856c5e8d-9b42-4339-ba49-e4fec265e22d
		summarizeBy: sum
		sourceColumn: n_treatment

		annotation SummarizationSetBy = Automatic

	column statistical_test
		dataType: string
		lineageTag: 83a8e000-ecf8-416f-b403-06f522d40d5f
		summarizeBy: none
		sourceColumn: statistical_test

		annotation SummarizationSetBy = Automatic

	column control_successes
		dataType: int64
		formatString: 0
		lineageTag: 39adc1e2-db7e-4714-8e48-44ee66d3cd5f
		summarizeBy: sum
		sourceColumn: control_successes

		annotation SummarizationSetBy = Automatic

	column treatment_successes
		dataType: int64
		formatString: 0
		lineageTag: 82bd073f-69dc-4750-ae16-e5ef92bfcf5b
		summarizeBy: sum
		sourceColumn: treatment_successes

		annotation SummarizationSetBy = Automatic

	column expected_additional_successes
		dataType: double
		lineageTag: 6d4c88e2-8a5c-4d93-b804-0ee9f4096d29
		summarizeBy: sum
		sourceColumn: expected_additional_successes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minimum_practical_lift
		dataType: double
		lineageTag: af1c6c58-405d-4580-9d89-0ce86bc4043e
		summarizeBy: sum
		sourceColumn: minimum_practical_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column decision_rule
		dataType: string
		lineageTag: 128d8777-cb65-4ac6-aace-6125dcd0d54b
		summarizeBy: none
		sourceColumn: decision_rule

		annotation SummarizationSetBy = Automatic

	column business_decision
		dataType: string
		lineageTag: 8a830738-cde7-4c09-bb3a-f78fd00f3231
		summarizeBy: none
		sourceColumn: business_decision

		annotation SummarizationSetBy = Automatic

	column random_state
		dataType: int64
		formatString: 0
		lineageTag: 147eaff5-2985-49bf-9a0f-238f6bb85d0e
		summarizeBy: sum
		sourceColumn: random_state

		annotation SummarizationSetBy = Automatic

	column control_success_rate
		dataType: double
		lineageTag: e72716dd-ae8a-41dd-ab86-3489a05fa035
		summarizeBy: sum
		sourceColumn: control_success_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column treatment_success_rate
		dataType: double
		lineageTag: f1817696-6bf0-4962-98a6-fdef4f17674b
		summarizeBy: sum
		sourceColumn: treatment_success_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column absolute_lift
		dataType: double
		lineageTag: 75551813-8682-47f5-b2d5-aefbbeece433
		summarizeBy: sum
		sourceColumn: absolute_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column relative_lift
		dataType: double
		lineageTag: 0a2e8068-57a1-413d-9dcc-fd6cd715451b
		summarizeBy: sum
		sourceColumn: relative_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_95_lower
		dataType: double
		lineageTag: 75d8b3ba-104f-44a1-8dd5-b05adc91425a
		summarizeBy: sum
		sourceColumn: ci_95_lower

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_95_upper
		dataType: double
		lineageTag: 3803aabd-9861-4a54-a7b4-ef12ce1b051d
		summarizeBy: sum
		sourceColumn: ci_95_upper

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column z_score
		dataType: double
		lineageTag: f89ed989-cd8b-438f-a73c-4f0d5007adac
		summarizeBy: sum
		sourceColumn: z_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column p_value
		dataType: double
		lineageTag: 7b59c920-26a9-4529-8d5d-b777b24a16d4
		summarizeBy: sum
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column significant_at_05
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 121d08dd-5d80-49e7-b643-bd3edfbbdd93
		summarizeBy: none
		sourceColumn: significant_at_05

		annotation SummarizationSetBy = Automatic

	partition ab_test_simulated_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_simulated_results.csv"),[Delimiter=",", Columns=22, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"experiment_id", type text}, {"scenario", type text}, {"scenario_type", type text}, {"n_control", Int64.Type}, {"n_treatment", Int64.Type}, {"statistical_test", type text}, {"control_successes", Int64.Type}, {"treatment_successes", Int64.Type}, {"expected_additional_successes", type number}, {"minimum_practical_lift", type number}, {"decision_rule", type text}, {"business_decision", type text}, {"random_state", Int64.Type}, {"control_success_rate", type number}, {"treatment_success_rate", type number}, {"absolute_lift", type number}, {"relative_lift", type number}, {"ci_95_lower", type number}, {"ci_95_upper", type number}, {"z_score", type number}, {"p_value", type number}, {"significant_at_05", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

