table ab_test_balance
	lineageTag: 9c14bac4-b5db-4b59-9300-19b99df58123

	column feature_type
		dataType: string
		lineageTag: 942da00d-f4a7-40ab-b2f5-3b09c5dac7a4
		summarizeBy: none
		sourceColumn: feature_type

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: ac43782e-b7db-424c-b863-c9971f982166
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column level
		dataType: string
		lineageTag: 2eeb8ded-8ed8-4652-a875-020e37f0e924
		summarizeBy: none
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column control_n
		dataType: int64
		formatString: 0
		lineageTag: e7244d00-c427-44a3-8922-405edb50652c
		summarizeBy: sum
		sourceColumn: control_n

		annotation SummarizationSetBy = Automatic

	column treatment_n
		dataType: int64
		formatString: 0
		lineageTag: d0fda6db-61fa-4527-bdff-68f4d6511584
		summarizeBy: sum
		sourceColumn: treatment_n

		annotation SummarizationSetBy = Automatic

	column control_rate_or_mean
		dataType: double
		lineageTag: 70605faa-dab6-4770-b314-03c773e57856
		summarizeBy: sum
		sourceColumn: control_rate_or_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column treatment_rate_or_mean
		dataType: double
		lineageTag: 4ac5de30-a612-4841-8fa8-97b7bf5eff15
		summarizeBy: sum
		sourceColumn: treatment_rate_or_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column absolute_difference
		dataType: double
		lineageTag: eeaca60e-615c-4b03-9b95-d1c8667b93da
		summarizeBy: sum
		sourceColumn: absolute_difference

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column standardized_difference
		dataType: double
		lineageTag: 24ca4728-570e-431a-a031-e284e7c63a67
		summarizeBy: sum
		sourceColumn: standardized_difference

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column passed_balance_check
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2594b1a4-693f-4840-b96f-481c42d3b50c
		summarizeBy: none
		sourceColumn: passed_balance_check

		annotation SummarizationSetBy = Automatic

	partition ab_test_balance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ab_test_balance.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"feature_type", type text}, {"feature", type text}, {"level", type text}, {"control_n", Int64.Type}, {"treatment_n", Int64.Type}, {"control_rate_or_mean", type number}, {"treatment_rate_or_mean", type number}, {"absolute_difference", type number}, {"standardized_difference", type number}, {"passed_balance_check", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

