table ablation_results
	lineageTag: a2c17c48-87d1-4659-b523-d6ce0417b0f1

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: d50434bc-a054-49df-9a8a-5b7ef0de4359
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 0ff3964d-66aa-46f7-a8bf-e75331b6916b
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column feature_group
		dataType: string
		lineageTag: 568d5dcf-f99c-43a6-8a06-0b866b715aa9
		summarizeBy: none
		sourceColumn: feature_group

		annotation SummarizationSetBy = Automatic

	column feature_count
		dataType: int64
		formatString: 0
		lineageTag: 1d132ee5-7be1-47e3-9530-b37450ad3960
		summarizeBy: sum
		sourceColumn: feature_count

		annotation SummarizationSetBy = Automatic

	column selected_threshold
		dataType: double
		lineageTag: a9f43382-239e-4fe6-baec-8a3a4528b810
		summarizeBy: sum
		sourceColumn: selected_threshold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_precision
		dataType: double
		lineageTag: a4b92eb6-bbf1-46db-9b07-8fffc28f6fd3
		summarizeBy: sum
		sourceColumn: validation_precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_recall
		dataType: double
		lineageTag: eecc213e-62a7-4e77-af06-ec8d96637be5
		summarizeBy: sum
		sourceColumn: validation_recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_f2
		dataType: double
		lineageTag: cd5c6c8b-0b8e-4e5c-abb9-9ea0578bd61c
		summarizeBy: sum
		sourceColumn: validation_f2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_roc_auc
		dataType: double
		lineageTag: ba0df4fc-55d8-4d1a-8a06-6093d0250431
		summarizeBy: sum
		sourceColumn: validation_roc_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_pr_auc
		dataType: double
		lineageTag: dbcb5a37-76ff-4bb0-b192-0605b2e88447
		summarizeBy: sum
		sourceColumn: validation_pr_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column test_precision
		dataType: double
		lineageTag: 8f903105-9e9b-4c90-92ad-2acf91458fec
		summarizeBy: sum
		sourceColumn: test_precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column test_recall
		dataType: double
		lineageTag: 0ce770fc-711f-4d75-95e0-d540cbab6215
		summarizeBy: sum
		sourceColumn: test_recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column test_f2
		dataType: double
		lineageTag: cd94332f-f960-49ab-aa3a-ff9b1d64b7db
		summarizeBy: sum
		sourceColumn: test_f2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column test_roc_auc
		dataType: double
		lineageTag: 2f23191f-6de3-4ad4-b8df-fa3c83541b70
		summarizeBy: sum
		sourceColumn: test_roc_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column test_pr_auc
		dataType: double
		lineageTag: f2f2710b-1aff-43fe-94f6-7b90f01dc6c2
		summarizeBy: sum
		sourceColumn: test_pr_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ablation_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\ablation_results.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"horizon_day", Int64.Type}, {"model", type text}, {"feature_group", type text}, {"feature_count", Int64.Type}, {"selected_threshold", type number}, {"validation_precision", type number}, {"validation_recall", type number}, {"validation_f2", type number}, {"validation_roc_auc", type number}, {"validation_pr_auc", type number}, {"test_precision", type number}, {"test_recall", type number}, {"test_f2", type number}, {"test_roc_auc", type number}, {"test_pr_auc", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

