table champion_test_metrics
	lineageTag: 94c22072-cdf1-4a9c-ac24-cac89ce172c7

	column split
		dataType: string
		lineageTag: 8575091e-becf-4f57-9b56-f85f262a04f6
		summarizeBy: none
		sourceColumn: split

		annotation SummarizationSetBy = Automatic

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: 8539cbdc-8ff4-4bb5-be17-8d199a862adf
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: b533a5d6-d7cd-4911-97ca-ff0824e919d4
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column threshold
		dataType: double
		lineageTag: 62cccf10-4a24-4877-a1f4-6a9800f3d242
		summarizeBy: sum
		sourceColumn: threshold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accuracy
		dataType: double
		lineageTag: 37c2d263-3662-4b9d-9b94-b74458505534
		summarizeBy: sum
		sourceColumn: accuracy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precision
		dataType: double
		lineageTag: 38c762b9-822e-4671-b568-0f80ef9b03cf
		summarizeBy: sum
		sourceColumn: precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall
		dataType: double
		lineageTag: a7f16a90-2331-4eb9-affe-44baac8fb2fd
		summarizeBy: sum
		sourceColumn: recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f1
		dataType: double
		lineageTag: 667bf294-789e-412d-bd48-e583fcf7b84d
		summarizeBy: sum
		sourceColumn: f1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f2
		dataType: double
		lineageTag: 584b05fe-7a28-46ba-9b1e-ad1d5e46a5bd
		summarizeBy: sum
		sourceColumn: f2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roc_auc
		dataType: double
		lineageTag: bfdb785b-762e-4d09-8567-518ee39d2c07
		summarizeBy: sum
		sourceColumn: roc_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pr_auc
		dataType: double
		lineageTag: b16904dd-da18-4b39-9ce0-035d32af298b
		summarizeBy: sum
		sourceColumn: pr_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brier_score
		dataType: double
		lineageTag: 9bf038cb-b609-4dc5-95a9-13964d7b8918
		summarizeBy: sum
		sourceColumn: brier_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tn
		dataType: int64
		formatString: 0
		lineageTag: 26b7a3bd-528e-49f7-856c-0bb6e4857e71
		summarizeBy: sum
		sourceColumn: tn

		annotation SummarizationSetBy = Automatic

	column fp
		dataType: int64
		formatString: 0
		lineageTag: e45f3ce4-b677-412c-9339-6e9df7181da0
		summarizeBy: sum
		sourceColumn: fp

		annotation SummarizationSetBy = Automatic

	column fn
		dataType: int64
		formatString: 0
		lineageTag: 6868a91b-eb1c-47ac-a59a-f5d254da371e
		summarizeBy: sum
		sourceColumn: fn

		annotation SummarizationSetBy = Automatic

	column tp
		dataType: int64
		formatString: 0
		lineageTag: f9a7c41b-147c-4e61-8894-ad40f3815424
		summarizeBy: sum
		sourceColumn: tp

		annotation SummarizationSetBy = Automatic

	partition champion_test_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\champion_test_metrics.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"split", type text}, {"horizon_day", Int64.Type}, {"model", type text}, {"threshold", type number}, {"accuracy", type number}, {"precision", type number}, {"recall", type number}, {"f1", type number}, {"f2", type number}, {"roc_auc", type number}, {"pr_auc", type number}, {"brier_score", type number}, {"tn", Int64.Type}, {"fp", Int64.Type}, {"fn", Int64.Type}, {"tp", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

