table champion_metric_bootstrap_ci
	lineageTag: 8662e3fa-c64e-470c-baa5-3e7a83969a49

	column metric
		dataType: string
		lineageTag: a3e61453-b876-4ed8-ab18-8cf1e42d70cb
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column point_estimate
		dataType: double
		lineageTag: fc4e5672-cdd4-4248-868e-6361d8b0c360
		summarizeBy: sum
		sourceColumn: point_estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_95_lower
		dataType: double
		lineageTag: d3d87427-ffe1-4c5a-81e6-cb97d37cfb4c
		summarizeBy: sum
		sourceColumn: ci_95_lower

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_95_upper
		dataType: double
		lineageTag: 08ab57e5-2685-483e-a2ca-a0f8c3726a4b
		summarizeBy: sum
		sourceColumn: ci_95_upper

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bootstrap_mean
		dataType: double
		lineageTag: 7e80cfda-06b6-4554-a428-a319f87ff6a3
		summarizeBy: sum
		sourceColumn: bootstrap_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bootstrap_std
		dataType: double
		lineageTag: 0655623b-66bb-43d6-bca8-f95c6c3e0235
		summarizeBy: sum
		sourceColumn: bootstrap_std

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column n_boot
		dataType: int64
		formatString: 0
		lineageTag: a1b2677c-b2a6-4e9b-9478-fb6ecbdfdd39
		summarizeBy: sum
		sourceColumn: n_boot

		annotation SummarizationSetBy = Automatic

	column random_state
		dataType: int64
		formatString: 0
		lineageTag: 75e96ef6-cea6-4132-ac65-ae843333d826
		summarizeBy: sum
		sourceColumn: random_state

		annotation SummarizationSetBy = Automatic

	partition champion_metric_bootstrap_ci = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\champion_metric_bootstrap_ci.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"metric", type text}, {"point_estimate", type number}, {"ci_95_lower", type number}, {"ci_95_upper", type number}, {"bootstrap_mean", type number}, {"bootstrap_std", type number}, {"n_boot", Int64.Type}, {"random_state", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

