table cluster_profiles
	lineageTag: 81ec16b6-864f-41f3-a2aa-b743ee38d4c5

	column cluster_id
		dataType: int64
		formatString: 0
		lineageTag: ccef5a57-2fc4-4abe-81fc-ce1d02c11ca4
		summarizeBy: sum
		sourceColumn: cluster_id

		annotation SummarizationSetBy = Automatic

	column enrollments
		dataType: int64
		formatString: 0
		lineageTag: c67f0aa1-862a-481b-ad7d-8ca0a7447fff
		summarizeBy: sum
		sourceColumn: enrollments

		annotation SummarizationSetBy = Automatic

	column at_risk_rate
		dataType: double
		lineageTag: 477be2a1-5be6-4490-bab7-5953ad16c1e4
		summarizeBy: sum
		sourceColumn: at_risk_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column median_total_clicks
		dataType: int64
		formatString: 0
		lineageTag: b4cb46f1-4ac6-4788-a508-8a3e2911b56a
		summarizeBy: sum
		sourceColumn: median_total_clicks

		annotation SummarizationSetBy = Automatic

	column median_active_days
		dataType: int64
		formatString: 0
		lineageTag: 377c7fc6-092d-4ee0-bcf7-2be7289e3d28
		summarizeBy: sum
		sourceColumn: median_active_days

		annotation SummarizationSetBy = Automatic

	column median_early_engagement_ratio
		dataType: double
		lineageTag: bc47bf3a-fec3-4de8-88c2-101977138d33
		summarizeBy: sum
		sourceColumn: median_early_engagement_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column median_avg_score
		dataType: int64
		formatString: 0
		lineageTag: e32e25f6-87bf-48fb-a588-59f3d9288fb3
		summarizeBy: sum
		sourceColumn: median_avg_score

		annotation SummarizationSetBy = Automatic

	column median_completion_ratio
		dataType: double
		lineageTag: 0a0712e5-3972-44fd-8358-89db246deeab
		summarizeBy: sum
		sourceColumn: median_completion_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column median_assessment_discipline
		dataType: double
		lineageTag: d6fa05b7-7c5d-4aed-8653-fe731105b2aa
		summarizeBy: sum
		sourceColumn: median_assessment_discipline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column median_persistence_score
		dataType: double
		lineageTag: 7579f23f-7ceb-4f96-a37c-89dc22d5d151
		summarizeBy: sum
		sourceColumn: median_persistence_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cluster_label
		dataType: string
		lineageTag: 07007321-a6bf-4a0d-a920-b860e59cc70a
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column share_of_dataset
		dataType: double
		lineageTag: 9e1b2a8f-d7f6-49e4-83ac-b640492c7795
		summarizeBy: sum
		sourceColumn: share_of_dataset

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cluster_profiles = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\cluster_profiles.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cluster_id", Int64.Type}, {"enrollments", Int64.Type}, {"at_risk_rate", type number}, {"median_total_clicks", Int64.Type}, {"median_active_days", Int64.Type}, {"median_early_engagement_ratio", type number}, {"median_avg_score", Int64.Type}, {"median_completion_ratio", type number}, {"median_assessment_discipline", type number}, {"median_persistence_score", type number}, {"cluster_label", type text}, {"share_of_dataset", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

