table cluster_profiles_long
	lineageTag: e0896a81-0ca7-4b55-ab60-73c0872fe948

	column cluster_label
		dataType: string
		lineageTag: 29b23ffe-deea-4e8c-9466-caa0534fe2b0
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column metric
		dataType: string
		lineageTag: 7f0320e6-987c-4505-8e10-7e6ebe6300d4
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column metric_value
		dataType: double
		lineageTag: f85c0f47-ec58-48db-b322-43afd17dc674
		summarizeBy: sum
		sourceColumn: metric_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cluster_profiles_long = m
		mode: import
		source =
				let
				    Source = cluster_profiles,
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(Source, {"cluster_label"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "metric"}, {"Value", "metric_value"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

