table MetricGlossary
	lineageTag: 2c9baf3c-6372-4b56-ae27-a875c3fb5e0c

	column Metric
		dataType: string
		lineageTag: 4d74dc8f-846a-4da8-8c00-bf5764ce76a1
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Definition
		dataType: string
		lineageTag: 21df9a20-9e22-4ca1-9db3-62296230a410
		summarizeBy: none
		sourceColumn: Definition

		annotation SummarizationSetBy = Automatic

	column Formula
		dataType: string
		lineageTag: e804a9b2-fec9-44db-96cf-617491a2381b
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = Automatic

	column WhyItMatters
		dataType: string
		lineageTag: 656599a5-d17e-4511-a785-bcebe1332300
		summarizeBy: none
		sourceColumn: WhyItMatters

		annotation SummarizationSetBy = Automatic

	column 'Used in Page'
		dataType: string
		lineageTag: d30912aa-60c9-453e-9f7d-638368d6f89a
		summarizeBy: none
		sourceColumn: Used in Page

		annotation SummarizationSetBy = Automatic

	partition MetricGlossary = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bVNPaxQxFP8qjz1ZTCmIotfaP5e6Om4rHtoeMpns5LEzyTSTqa0noQcPIlrQgxQPaxFRKCoK0p3jLP0e4yfxJbutq+wlDJPk9/dle7sTWSmwRKPZTmfLGp1C2dbHkElutbQQt/UL6Gc8ZRBzA1ph86UCnV58a+v3CE61ozPnr3wH7hYtloOdDtuKYAmu0Xod1qMFNn5tYHzc1u9AqOZMKzhohgJEW3/iYCpnJReK2COeSrjJ4PZOp7PLtjs9KXiWzZc1h5dBbhKZkeLRV0d8XuGpmFH9n7D7C+xhxTU429YvCV8oA4SeHcIT4kCdzpG0foOtL5bCWOkNjX450LTSZRu0groYaiiuEn0sMVVOJjC9xCLVnIMiXQUMFEKOZUm7UwN/zZFTDYPmc84mAiZxPFhZXH60wjbI+ino8RHRFqr5oCHGtn7uQHGErK1PCtbjekAGIJfOogj5l7LglseYoTv0BG9pe69qhm6Oy6gXiC5R9ioebiU+0RMEkfGyBMxjnnEtJFumAqHSCSmPeiAquy/ZFllwkzimuoPhwpTocF9OMfZm8p+j465FwtwMyW2SuTABYXbKqh19dJD4+sfHphlq1pWEVRKipUQLa+JLs9JaYykDOqQgxWYIVBXGljtfUeC8FehWZn8TCgpfXWhGND9Iv88WTFxKcjjdGKjmJ2n//ezNv8PkzSbNuZ8Mf2xGzyzjZq9LxvIik9DzvNDFMueOXoMH3KBaj3KC5GC5TkyOT4M4WF66O0G5E1C6q2usixrzKodV6aRwPCbEtX6fPgPSPezTpJL+V371ycmDQlrMpXbBGz2n+shP05BK89Okrwh2/wA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Metric,Definition,Formula,WhyItMatters,UsedInPage" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric,Definition,Formula,WhyItMatters,UsedInPage", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Metric,Definition,Formula,WhyItMatters,UsedInPage", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Metric,Definition,Formula,WhyItMatters,UsedInPage.1", "Metric,Definition,Formula,WhyItMatters,UsedInPage.2", "Metric,Definition,Formula,WhyItMatters,UsedInPage.3", "Metric,Definition,Formula,WhyItMatters,UsedInPage.4", "Metric,Definition,Formula,WhyItMatters,UsedInPage.5"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Metric,Definition,Formula,WhyItMatters,UsedInPage.1", type text}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.2", type text}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.3", type text}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.4", type text}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.5", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Metric,Definition,Formula,WhyItMatters,UsedInPage.1", "Metric"}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.2", "Definition"}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.3", "Formula"}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.4", "WhyItMatters"}, {"Metric,Definition,Formula,WhyItMatters,UsedInPage.5", "Used in Page"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

