table model_feature_importance
	lineageTag: 4a20a00f-5e99-4e18-8395-7bdf9811ce8b

	column feature
		dataType: string
		lineageTag: 29dfedc4-5b54-4294-874e-cf9272e104f2
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column native_importance
		dataType: double
		lineageTag: a8b61250-751f-40f0-9b68-47dc8fa51f56
		summarizeBy: sum
		sourceColumn: native_importance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column permutation_importance_mean
		dataType: double
		lineageTag: 1a801d2b-8dc3-45dd-b959-887af2795bb7
		summarizeBy: sum
		sourceColumn: permutation_importance_mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column permutation_importance_std
		dataType: double
		lineageTag: bf46f670-75cd-46b3-866f-b69ceafec0d6
		summarizeBy: sum
		sourceColumn: permutation_importance_std

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column original_feature_name
		dataType: string
		lineageTag: e2c44203-b8d3-4007-84d4-1733d3cd676b
		summarizeBy: none
		sourceColumn: original_feature_name

		annotation SummarizationSetBy = Automatic

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: e6febda4-b6cc-491e-af1a-0bd2b2207647
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 9b67378f-9857-4daf-8213-2b415b42c2a8
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column importance_rank
		dataType: int64
		formatString: 0
		lineageTag: 3750abfe-0230-467c-ae7d-759ba3c670bd
		summarizeBy: sum
		sourceColumn: importance_rank

		annotation SummarizationSetBy = Automatic

	partition model_feature_importance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\model_feature_importance.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"feature", type text}, {"native_importance", type number}, {"permutation_importance_mean", type number}, {"permutation_importance_std", type number}, {"original_feature_name", type text}, {"horizon_day", Int64.Type}, {"model", type text}, {"importance_rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

