table outcome_risk_summary
	lineageTag: ed936d04-ab0c-465b-bc10-a4b3c624a97f

	column final_result
		dataType: string
		lineageTag: e19cebb9-a21a-4bfd-908e-c66bf293ac8d
		summarizeBy: none
		sourceColumn: final_result

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: 1f9879be-171f-4365-8d60-06c7d100c4e9
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column predicted_positive_rate
		dataType: double
		lineageTag: 62b32999-658a-4def-81bb-b09f6921cb4c
		summarizeBy: sum
		sourceColumn: predicted_positive_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column average_risk_probability
		dataType: double
		lineageTag: 4beff8f8-f58b-4429-ab70-59f50c52594d
		summarizeBy: sum
		sourceColumn: average_risk_probability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition outcome_risk_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\outcome_risk_summary.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"final_result", type text}, {"n", Int64.Type}, {"predicted_positive_rate", type number}, {"average_risk_probability", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

