table personalized_learning_paths
	lineageTag: 83edf8da-d4c0-4976-bea5-03c77b2d13e4

	column id_student
		dataType: int64
		formatString: 0
		lineageTag: 309f234e-298b-4bef-a7e9-007d9edbc8c7
		summarizeBy: sum
		sourceColumn: id_student

		annotation SummarizationSetBy = Automatic

	column code_module
		dataType: string
		lineageTag: 9747797e-0d0a-4893-a1d5-9498ae93aca9
		summarizeBy: none
		sourceColumn: code_module

		annotation SummarizationSetBy = Automatic

	column code_presentation
		dataType: string
		lineageTag: 1db00956-8ba0-45d9-a01d-53a01c9fa8e8
		summarizeBy: none
		sourceColumn: code_presentation

		annotation SummarizationSetBy = Automatic

	column final_result
		dataType: string
		lineageTag: 0c1d90b2-34c8-4f37-b83e-045497496324
		summarizeBy: none
		sourceColumn: final_result

		annotation SummarizationSetBy = Automatic

	column at_risk
		dataType: int64
		formatString: 0
		lineageTag: 021f4abb-7166-4a43-97ce-7b828b90dfe4
		summarizeBy: sum
		sourceColumn: at_risk

		annotation SummarizationSetBy = Automatic

	column rule_segment
		dataType: string
		lineageTag: 241b76f9-8950-42bb-8bac-0bae7cc6ce62
		summarizeBy: none
		sourceColumn: rule_segment

		annotation SummarizationSetBy = Automatic

	column cluster_id
		dataType: int64
		formatString: 0
		lineageTag: 8d0f0a66-9add-404b-a7ac-c14775e13ff0
		summarizeBy: sum
		sourceColumn: cluster_id

		annotation SummarizationSetBy = Automatic

	column cluster_label
		dataType: string
		lineageTag: 2f3d77d9-d980-4de9-aaf8-c7efc6f95491
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column total_clicks
		dataType: int64
		formatString: 0
		lineageTag: 4116e5d4-b2b6-4825-835e-7d038c770799
		summarizeBy: sum
		sourceColumn: total_clicks

		annotation SummarizationSetBy = Automatic

	column active_days
		dataType: int64
		formatString: 0
		lineageTag: 88f89ef0-0d3d-4184-bcf3-f079459db779
		summarizeBy: sum
		sourceColumn: active_days

		annotation SummarizationSetBy = Automatic

	column avg_score
		dataType: int64
		formatString: 0.0
		lineageTag: beb6956f-43f9-481e-ac14-d1e4366dd7aa
		summarizeBy: sum
		sourceColumn: avg_score

		annotation SummarizationSetBy = Automatic

	column completion_ratio
		dataType: double
		lineageTag: b6edbfa2-eb71-4f4c-af58-39c1ed0cd645
		summarizeBy: sum
		sourceColumn: completion_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assessment_discipline
		dataType: double
		lineageTag: 452cf156-8a86-4f79-ac5a-72fcb21f7d14
		summarizeBy: sum
		sourceColumn: assessment_discipline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column persistence_score
		dataType: double
		lineageTag: 8863ce78-1077-4552-b0f8-899bbd8190ec
		summarizeBy: sum
		sourceColumn: persistence_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column peer_similarity_score
		dataType: double
		lineageTag: ed60a66c-9f38-4a0a-a930-18ea66399136
		summarizeBy: sum
		sourceColumn: peer_similarity_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column engagement_fit_score
		dataType: double
		lineageTag: e2c13064-9d0c-4f40-a330-c27c170aec1b
		summarizeBy: sum
		sourceColumn: engagement_fit_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column completion_probability_proxy
		dataType: double
		lineageTag: d3676d26-c39e-46ad-9456-d3407ef1c1c1
		summarizeBy: sum
		sourceColumn: completion_probability_proxy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gap_feature_1
		dataType: string
		lineageTag: cc48900f-089b-40ed-a910-75aa69e0c402
		summarizeBy: none
		sourceColumn: gap_feature_1

		annotation SummarizationSetBy = Automatic

	column gap_feature_2
		dataType: string
		lineageTag: 6264e4bf-c2fd-492f-8887-10aa74269d7a
		summarizeBy: none
		sourceColumn: gap_feature_2

		annotation SummarizationSetBy = Automatic

	column gap_feature_3
		dataType: string
		lineageTag: 58c8f328-6f82-4e58-b493-e67e1f472dde
		summarizeBy: none
		sourceColumn: gap_feature_3

		annotation SummarizationSetBy = Automatic

	column recommended_path
		dataType: string
		lineageTag: 71564324-5fda-48be-be22-37edecb298e6
		summarizeBy: none
		sourceColumn: recommended_path

		annotation SummarizationSetBy = Automatic

	column action_1
		dataType: string
		lineageTag: d96dd384-f30b-4519-88e8-581928c9c931
		summarizeBy: none
		sourceColumn: action_1

		annotation SummarizationSetBy = Automatic

	column action_2
		dataType: string
		lineageTag: 5037c77b-a966-4c3a-916c-c2c034129253
		summarizeBy: none
		sourceColumn: action_2

		annotation SummarizationSetBy = Automatic

	column action_3
		dataType: string
		lineageTag: cf699308-6565-4f36-9247-01a68e4bb261
		summarizeBy: none
		sourceColumn: action_3

		annotation SummarizationSetBy = Automatic

	column activity_type_1
		dataType: string
		lineageTag: cd0a617f-7010-4a61-87c7-66dd151e3073
		summarizeBy: none
		sourceColumn: activity_type_1

		annotation SummarizationSetBy = Automatic

	column activity_type_2
		dataType: string
		lineageTag: 1ea7fa94-2411-4b07-b60e-cd97c3d94351
		summarizeBy: none
		sourceColumn: activity_type_2

		annotation SummarizationSetBy = Automatic

	column activity_type_3
		dataType: string
		lineageTag: 5f94f010-914a-4f88-a666-106641255c8b
		summarizeBy: none
		sourceColumn: activity_type_3

		annotation SummarizationSetBy = Automatic

	column activity_recommendation_1
		dataType: string
		lineageTag: e45d5858-8d77-47db-b3d2-691bbc35170c
		summarizeBy: none
		sourceColumn: activity_recommendation_1

		annotation SummarizationSetBy = Automatic

	column activity_recommendation_2
		dataType: string
		lineageTag: 4064cb78-4181-4b78-959e-017e762d7765
		summarizeBy: none
		sourceColumn: activity_recommendation_2

		annotation SummarizationSetBy = Automatic

	column activity_recommendation_3
		dataType: string
		lineageTag: 5a863e37-6eca-4ef6-8f39-14979bf2d79e
		summarizeBy: none
		sourceColumn: activity_recommendation_3

		annotation SummarizationSetBy = Automatic

	column accessibility_score
		dataType: int64
		formatString: 0
		lineageTag: 1c5fcc05-afcd-42d6-911d-394a0f0fc4b2
		summarizeBy: sum
		sourceColumn: accessibility_score

		annotation SummarizationSetBy = Automatic

	column recommendation_score
		dataType: double
		lineageTag: 31d322fb-db92-4efc-a2e9-21ceb6b562f1
		summarizeBy: sum
		sourceColumn: recommendation_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EnrollmentKey
		dataType: string
		lineageTag: 1b440bb8-8713-4144-a273-c5e78fe51f0d
		summarizeBy: none
		sourceColumn: EnrollmentKey

		annotation SummarizationSetBy = Automatic

	partition personalized_learning_paths = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\personalized_learning_paths.csv"),[Delimiter=",", Columns=32, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_student", Int64.Type}, {"code_module", type text}, {"code_presentation", type text}, {"final_result", type text}, {"at_risk", Int64.Type}, {"rule_segment", type text}, {"cluster_id", Int64.Type}, {"cluster_label", type text}, {"total_clicks", Int64.Type}, {"active_days", Int64.Type}, {"avg_score", Int64.Type}, {"completion_ratio", type number}, {"assessment_discipline", type number}, {"persistence_score", type number}, {"peer_similarity_score", type number}, {"engagement_fit_score", type number}, {"completion_probability_proxy", type number}, {"gap_feature_1", type text}, {"gap_feature_2", type text}, {"gap_feature_3", type text}, {"recommended_path", type text}, {"action_1", type text}, {"action_2", type text}, {"action_3", type text}, {"activity_type_1", type text}, {"activity_type_2", type text}, {"activity_type_3", type text}, {"activity_recommendation_1", type text}, {"activity_recommendation_2", type text}, {"activity_recommendation_3", type text}, {"accessibility_score", Int64.Type}, {"recommendation_score", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "EnrollmentKey", each Text.From([id_student]) & "|" & [code_module] & "|" & [code_presentation]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"EnrollmentKey", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

