table 'Playbook Table'
	lineageTag: 70af779c-8583-49eb-9a9e-360b9afbac27

	column TableName
		dataType: string
		lineageTag: 2db3f7f6-1e47-42de-a804-5284ea19deca
		summarizeBy: none
		sourceColumn: TableName

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: 21a8d2a9-69ef-4ad4-aceb-19deabc7dc3a
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column Grain
		dataType: string
		lineageTag: 23f19009-df49-4a5d-b588-ff1533539d94
		summarizeBy: none
		sourceColumn: Grain

		annotation SummarizationSetBy = Automatic

	column UsedInPage
		dataType: string
		lineageTag: 0a330653-9742-4dff-8ba9-b9a337ee743b
		summarizeBy: none
		sourceColumn: UsedInPage

		annotation SummarizationSetBy = Automatic

	partition 'Playbook Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("3Vrdctu4FX4VTG4rxY6Tze4kV/5tOl03Xjs725l0hwORkISGIliAtKNc7Tv0Dfsk/c4BQIKUZCuO04ve2BKJn3M+nPOdH+jjx2dzJZvWKpfNdSXLZ5Nnl1JXYqaW8lYbK2RVCNM2uVkp0chZqcQcTwvlcqvrRt8qjJDlutG5eytyUzWY7USppK0UZucYopv1REjnlHMrVTUTwTsJ7NmW+EY7yGZqtfskSjlT5XMIcV5ZU5Y0/I3QReaatsBn8SdsUahsZYoWkoRvNVbCS9loU2HqlVwo8UKcf1Z5ywK+v1X2Vqu7t4JfHYmTqNw/2sPDo9fifdDvuNfk3QtxJhsZR1xZA9VX4kxBdk0bYciRuPDYifNqoSulrK4WccbPSn6i3U4BCVTBcH7GqLx8ffjs98nHZ04tSMMM2OhFRR8d5D9uGpkvVQ9iGObBcYyXhfrTmXSq6N7qCgezYhBEY4TCGkJ1KH5nTF+KGy+G3z+ipqwzwFR/gZzXChhjSCE9fDzvtThuptd08hGb45xXOMVaygK1l6OJ4mez0Plb8eFD3JKhrJOtMgYOZ5HVslkSpKMlSrnGTsFY6cxsfA85ac6EDRcjXbtYKEcfnTdUO1zJ5caq/ztsh6bKWI8GXgEkxj1fylWNJ1kDmEizQvMmhPoFu/lSlcUUDCJohOhHBDZpyYaJUu5kky9L7cAI0fAbq6HIJJ0UqMgfRnro8cQK7Wqc7/BMBF4M5XCqidD/IE6xxMwO4GXcTrCJ2xvNLaDFRe6FkIgvm2FU5trVSto1BLvhT9DLCQMteQZRJi3YaKg9gb/nZVuQ9Ua4ctMSuwKIFmMjpWIywQWbIjUClGTnoDQ506VnZ6BJIoiVapamIPRYeHq2h4k+COEedJrixbg0S/jJ0pRFlhvY1kxVGN0wOHVtbONENwKWIgs1NfO5j0ZOk7sWt9qRYRn7qTQSGpeyInefwItJeOGfArkXk8PDQ8QlWTo1laWyjWBdPDBOlYohC0cByGujPad+6EQgG/aBLfqEgNurEoSibcTwR1hBqQPsEY1TDJcIAPhQyxwvgNcr0a98w/v7mPOjuMByFUJpP9tPApiqFmc4HUZPzrxL9rEFMoRgdNBYBC52jP51Et0h4kLzl1KC/4poYQ5GB9CVRxLPjw9O2J3Y2+KkPuiE1TGQAtJnoKf58S1MW1adA/7E65z376+VhGFDRyj8k/hzaZyDW4iDdMzfDDZmTbsEZmngMaAi2LCEk0kS6jNEpYRkhVRDT8MIEabAY4Jb0DGXPmJPnZyrOGLqGhA8pTt0PjK3EAWWvBY/TsSLVxNx9MKbyMtDguCdXz7q9Upc8q7hsTiXtlyL33xs+ur8Af4R12fiLVsH3gHlmrkuFfFtCBPTUt3C7GIGB4MMY1LG9QdC2PCBJoNJUy+VmfssouMXvyVpeuo/4khC+hF1fkSw2jfER41dm+ewjSzmlhECEiGAIcKYeVv2tnunmyXUZZXCWt69I51AhhqWCUmBR3OnVMWEu+6X8MO7pWscmdsKRxwlEtmeFh4fOgYvskK65cxIuxlJ1ol3j1IYyncoaiLYzlp+spnnBJPq1hc5/rDm16PMCRCMU6ROlO+Q6NxnO7viLbNyRxb9oTM/0heynx2U7yIH5ABJY2XlSd6bRljTwcVoxi2E9psfxNwn1w5fKQDlsiwn4uLI88fV9fT419OEQ6abseMhOtkRMka8ETXLOs0yrxnZCpFdonyvwBgHHybIk1jOjlhJXlZIU/qr5xrLzUj3OOAAs2yp6RF4iJwovPkOuo+yCIed82U2W8ez7zXuBk39oFCbuo4rCyvv+vP7zx//9geIDxdHSfKRt/aWNF53+nJOReps6DftNv12JYdZOOKfRRHbZeBjO/TvE0YYJSx/vfqLd3BisSWC+C7LvX5/SmY7CebrTfnEaqpZY2F0UyPVeTOWYU+V90wud1v+JSt0yQp7pPqlEpJMN/CwBFoge9+WMYsZJRUUUYSZObCYKgYJt9sGRTz+0Tp71yHvfhAhnxklkMezUna20JcTW0oyWm7KiT6o17Fjz/vjT8ZO+sLMdnNqiBn6D/SMChFEDrmokJ/D4P73NddGzSADEllwYGqnhEeCavJ159kjH40Z4cKatn4rYEt3DgPuOkwQrv6FsopQB14VAXG3VNVwIsDBR6tWhgwC2CGuYHdVpMc/mPHEh9/pv8DA1MBjYGPOlh0kqmFOlzQcJ0SpIDi5DEQA4iMgBL09oCyc8v+HuGB7OPueSvuAHnbI9IqyOVnllHShdpiBATWZCwRvUhffZL60qI4CV3Kl4A1IickE+sUnVDiu2rBi+pz9Q1afSP2Q4D+xwspaY7NY6WYOOoQKgD/5OhaB2mkS2nusf1aphfTPSHtv0F6zUBKDDvzZr5ARyk9q5NR0og+JuNkKMXXoX/zihx6LpS6QIDChDDqh/iiBLPcy/RkOyxovXcI6bKJsxL7vkTQ9EuoOWIy6ITx20AjZYt3cn84R2mW+vrf2ebhFtE/1vlH3hJZXxsS+xaV7LVkdEFsXknw/IizwXPzqMy46+hiPgRtoDH5vN8AQGLKIUS6AG5Ziq7hIF9/fwh/qBA0TGp+rZDNjGlQoss5yja1O4ldq4s4p18yVd3LotTuxCYnR277ks0k3hou7Jn7LYeErX9x1i/g04mtbOXsf+kay4toZ8+V2twgvE18YFnlsvIk9dwydeIgfBoKvY3ubWYD6PrHS8cbEC8dGgI91z1MhBrz+pND0SQ13JsoM5/5PpHhm6AUUp8ZdjJJqGbymMi1mZ6RlhYDU3TjF2n5uzcq3diju0YdBUydGsOnjNP2mXk/s5fUttMx3pCDGmclbvjnaaMrRBgjwOBxE7Xyp8k/UXRf+ligNdaG7RSmvqXgp3w7LWV5mge4KqZNgOp71RN28qKuzq4yF7sPaNZGKuNRuRVcFXiU29rQlmW+0OB1VIEPhn1hWpBjBKU/8p0F8CgUFSTugW4BsVvpL6MJYU7Q5XefplS6ljXrwUfS69J4XzCk2+8K+EbGn1K42d6rPNmhxesCCXZ6dd131hHx2tojncxjV1OkvClWRqlBgmac2G71qOeNOKoCb+Iwy8qWmlq7OiSOCCEHymEe0sJc5HGRLaEEiWE/xvw1p3owaPcReRWDZoZk9tZJnevW+C7dn9NYN09n0Yj29LkYFCqaHPAh6pKKxhe/jbo3h3/3uPCpDecGJv2Hapk1feO6jypPeV8V8bpi/bVL+lhIUmvT3ANvUimVnolRQ5k28WqB/dL1A/+mKYSMafU3/5Nti1N6NRah60+XD2/S+5+cMpH9/kjf3XSnsOpt9bxHI7AbjuC+8wwDHze2dIo/b4F/d7X6MWrsa3FDlMqaq29RKk+FY34Zr8+5r56v4QhkDCDT8AmJYS5Pyl7vz4gGtbU9ySVr+eQQWeB8LxWKL2MkvKSaxeczPYViVcKXO4xWNHxRC41yXDVsyixp3Co0BP2uD3HoO2yStq+GvNx4WOf25xwOCp0O3iT/a+5FKkKEkj+gXXxUVd3whWI1bJNwxGnvCG1G3FkU1TqKRdqGa/gdjXEuozz5l8z/KCL/WQCC0REEVAtoOp3mMuXtbikbWq7OI0dTrEq47Q0t3r3Z20r9FOtBHjIm4ub6cxAyod4HEbUiXJKAH1g3DevDdDp+IF20fSPRTnGFpFn4bvtkOKhUh9yed+JicaW0e7nmR4VOBa+jTwkLzcAoytC5B87oR2t9xMO0mk0Vyh75fOM8ulXR0DU8Z0Kpu1gegFKRQlb9KSq6eTYUQhRLL2IWsKBU8O/479vOzSRAkPELWyMJymoQHvyH0UIeKavZtl99ZaapFl5j+0iog3la1vjV8i5V0ukeX5pPugmfWakS3eC0cL8yXlHfLOun6TIdNgDGJ33dZu3ETta/U/c9cwu1U6GMMyKREwKZ+B3U1MKcz8QNv4QcXR9QZ6pa65zpqpOIjb6V+/y8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [TableName = _t, Role = _t, Grain = _t, UsedInPage = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"TableName", type text}, {"Role", type text}, {"Grain", type text}, {"UsedInPage", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

