table risk_signal_trajectory
	lineageTag: 5655145c-0e48-40d5-b4cb-4893635c33a0

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: febe5bf0-7617-405d-8296-4e339881fed4
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: c9cc958e-e9d2-47e0-bc50-6249ed301b75
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column feature_label
		dataType: string
		lineageTag: efa22b6b-7237-4388-adfb-bc0f62432f3e
		summarizeBy: none
		sourceColumn: feature_label

		annotation SummarizationSetBy = Automatic

	column group
		dataType: string
		lineageTag: 498f0331-d528-4737-944f-16db88a24667
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column at_risk
		dataType: int64
		formatString: 0
		lineageTag: 8710d5cc-1897-4516-9547-70b8ca344094
		summarizeBy: sum
		sourceColumn: at_risk

		annotation SummarizationSetBy = Automatic

	column mean
		dataType: double
		lineageTag: 71d3604c-2e84-4c98-9b79-d31d6d9d2e69
		summarizeBy: sum
		sourceColumn: mean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sem
		dataType: double
		lineageTag: 8eb4590b-a431-4b5b-9ac0-e04b6623b0ed
		summarizeBy: sum
		sourceColumn: sem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column n
		dataType: int64
		formatString: 0
		lineageTag: 05659505-260b-4130-9432-e4bac217d3ba
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	partition risk_signal_trajectory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\risk_signal_trajectory.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"horizon_day", Int64.Type}, {"feature", type text}, {"feature_label", type text}, {"group", type text}, {"at_risk", Int64.Type}, {"mean", type number}, {"sem", type number}, {"n", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

