table risk_band_summary
	lineageTag: a3625c60-952f-4a69-b185-c22385a77220

	column risk_band
		dataType: string
		lineageTag: 3463a40b-a36e-45a5-8f14-73bebeba2f0f
		summarizeBy: none
		sourceColumn: risk_band

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: b3130042-7196-473b-b56c-580b56c4b43f
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column actual_at_risk_rate
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4fb14f11-3fda-40a3-ab77-9aad7f792a92
		summarizeBy: sum
		sourceColumn: actual_at_risk_rate

		annotation SummarizationSetBy = Automatic

	column average_predicted_probability
		dataType: double
		lineageTag: 044ce222-b465-4a07-ab19-413e55b82de0
		summarizeBy: sum
		sourceColumn: average_predicted_probability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column risk_band_method
		dataType: string
		lineageTag: f97f23c5-0c4a-40c3-9c49-6292a8ee075f
		summarizeBy: none
		sourceColumn: risk_band_method

		annotation SummarizationSetBy = Automatic

	column band_edges
		dataType: string
		lineageTag: 1c03a44f-8d7f-4a18-be72-e8fa070c6547
		summarizeBy: none
		sourceColumn: band_edges

		annotation SummarizationSetBy = Automatic

	partition risk_band_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\risk_band_summary.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"risk_band", type text}, {"n", Int64.Type}, {"actual_at_risk_rate", type number}, {"average_predicted_probability", type number}, {"risk_band_method", type text}, {"band_edges", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

