table segment_model_performance
	lineageTag: 7430ef7d-50cb-49ad-87eb-6603d5173aa8

	column cluster_label
		dataType: string
		lineageTag: 0beee40b-d0f0-4ff8-9dc2-357155d4628e
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: 1bf76412-9494-4004-abe0-2338b92b4021
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column actual_at_risk_rate
		dataType: double
		lineageTag: 60901352-73af-4ead-a93d-c364775221f9
		summarizeBy: sum
		sourceColumn: actual_at_risk_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column predicted_positive_rate
		dataType: double
		lineageTag: 8776ffc8-fe52-4176-8013-4df65addb72e
		summarizeBy: sum
		sourceColumn: predicted_positive_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column average_risk_probability
		dataType: double
		lineageTag: 0f052efc-7c2e-4bf5-bcb9-fd0e84cbdff9
		summarizeBy: sum
		sourceColumn: average_risk_probability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precision
		dataType: double
		lineageTag: de95c928-3a1a-49f1-aade-6cdd458621ad
		summarizeBy: sum
		sourceColumn: precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall
		dataType: double
		lineageTag: c1e4d8ab-2c23-4317-b644-eb75819f54b9
		summarizeBy: sum
		sourceColumn: recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accuracy
		dataType: double
		lineageTag: 73555887-3db2-493e-8961-674f6cca4e17
		summarizeBy: sum
		sourceColumn: accuracy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition segment_model_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\segment_model_performance.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cluster_label", type text}, {"n", Int64.Type}, {"actual_at_risk_rate", type number}, {"predicted_positive_rate", type number}, {"average_risk_probability", type number}, {"precision", type number}, {"recall", type number}, {"accuracy", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

