table subgroup_model_performance
	lineageTag: 085e55cc-bdaa-4074-9579-973cb07a2d79

	column subgroup
		dataType: string
		lineageTag: f2044027-48d0-4af0-abfa-942bf7f5249f
		summarizeBy: none
		sourceColumn: subgroup

		annotation SummarizationSetBy = Automatic

	column group
		dataType: string
		lineageTag: 72c93589-841d-440f-a75d-1af0fa560c97
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: 2f78d68f-74ee-437d-968c-8e9f94e28438
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column at_risk_rate
		dataType: double
		lineageTag: e5aed256-ac90-4a61-90b5-b80cb33ca9b9
		summarizeBy: sum
		sourceColumn: at_risk_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall
		dataType: double
		lineageTag: 69cae3d5-b0f5-4a81-b8d4-9ef0c28db8a0
		summarizeBy: sum
		sourceColumn: recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precision
		dataType: double
		lineageTag: 75c03691-d147-4915-963b-24a12f719cf5
		summarizeBy: sum
		sourceColumn: precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f1
		dataType: double
		lineageTag: 53301539-a969-4cb8-b06f-4499851b673f
		summarizeBy: sum
		sourceColumn: f1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roc_auc
		dataType: double
		lineageTag: 3066d022-6631-4196-aed8-ff3a0d3e0efb
		summarizeBy: sum
		sourceColumn: roc_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall_gap_to_target
		dataType: double
		lineageTag: 838df2a0-def0-472f-918f-7cf2f06c321c
		summarizeBy: sum
		sourceColumn: recall_gap_to_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bf7b9855-b75f-48b7-a53e-ec1ec7fd3024
		summarizeBy: none
		sourceColumn: review_flag

		annotation SummarizationSetBy = Automatic

	partition subgroup_model_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\subgroup_model_performance.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"subgroup", type text}, {"group", type text}, {"n", Int64.Type}, {"at_risk_rate", type number}, {"recall", type number}, {"precision", type number}, {"f1", type number}, {"roc_auc", type number}, {"recall_gap_to_target", type number}, {"review_flag", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

