table threshold_cost_benefit
	lineageTag: 04c793cb-e3f6-4348-8b57-c84949c3f91b

	column threshold
		dataType: double
		lineageTag: e1d520d4-0eb9-455c-a726-36ef9b3631ef
		summarizeBy: sum
		sourceColumn: threshold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accuracy
		dataType: double
		lineageTag: 077765a9-f612-4621-9bb2-34a7d3daafb4
		summarizeBy: sum
		sourceColumn: accuracy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precision
		dataType: double
		lineageTag: 5abe7c7f-29fb-450c-bde3-c3646f47d355
		summarizeBy: sum
		sourceColumn: precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall
		dataType: double
		lineageTag: c7acd26f-589e-4a70-8a7d-cc1c5c9861f4
		summarizeBy: sum
		sourceColumn: recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f1
		dataType: double
		lineageTag: 7a56db84-0cbc-4443-8e3b-716b5cc87887
		summarizeBy: sum
		sourceColumn: f1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f2
		dataType: double
		lineageTag: 219264c0-9677-4b60-a8ec-49ca6b5527b8
		summarizeBy: sum
		sourceColumn: f2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roc_auc
		dataType: double
		lineageTag: f5c929ae-f06d-4ea8-aee1-010154528f16
		summarizeBy: sum
		sourceColumn: roc_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pr_auc
		dataType: double
		lineageTag: cb4fbcf0-7337-4c58-8a8f-46d036775a5f
		summarizeBy: sum
		sourceColumn: pr_auc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brier_score
		dataType: double
		lineageTag: 5918a2b6-a58f-42ea-beb6-717c9f8539c9
		summarizeBy: sum
		sourceColumn: brier_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tn
		dataType: int64
		formatString: 0
		lineageTag: 1ebf0583-c605-4514-b424-b0bfb98ab54b
		summarizeBy: sum
		sourceColumn: tn

		annotation SummarizationSetBy = Automatic

	column fp
		dataType: int64
		formatString: 0
		lineageTag: dfef6f4c-d17d-4d4c-9ae9-5494409c7d20
		summarizeBy: sum
		sourceColumn: fp

		annotation SummarizationSetBy = Automatic

	column fn
		dataType: int64
		formatString: 0
		lineageTag: fa16804d-487a-436c-b695-76e791fd3235
		summarizeBy: sum
		sourceColumn: fn

		annotation SummarizationSetBy = Automatic

	column tp
		dataType: int64
		formatString: 0
		lineageTag: 4f49fac4-26a0-48e8-9b95-c15fe50461a8
		summarizeBy: sum
		sourceColumn: tp

		annotation SummarizationSetBy = Automatic

	column horizon_day
		dataType: int64
		formatString: 0
		lineageTag: 5e8bbe7f-a4dd-4dee-a0cf-5bbbea248f8e
		summarizeBy: none
		sourceColumn: horizon_day

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: b67e545c-b780-45a2-9b9b-a43dd2aeaa6d
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column total_flagged
		dataType: int64
		formatString: 0
		lineageTag: 93cdae8d-8191-4314-9c6a-15303bdd3930
		summarizeBy: sum
		sourceColumn: total_flagged

		annotation SummarizationSetBy = Automatic

	column flagged_pct
		dataType: double
		lineageTag: 01a710bb-b181-4042-9608-1d7857aee03c
		summarizeBy: sum
		sourceColumn: flagged_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column false_alert_ratio
		dataType: double
		lineageTag: 475adfa2-7fe6-41f4-95cb-fc983b5f18ca
		summarizeBy: sum
		sourceColumn: false_alert_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column missed_at_risk
		dataType: int64
		formatString: 0
		lineageTag: 1d61cb5f-bf77-4f17-a5ec-a7bd584324d1
		summarizeBy: sum
		sourceColumn: missed_at_risk

		annotation SummarizationSetBy = Automatic

	column expected_review_load_per_1000
		dataType: double
		lineageTag: b901bb94-eb3e-4a83-bdb8-1518d879b3be
		summarizeBy: sum
		sourceColumn: expected_review_load_per_1000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column caught_at_risk_per_1000
		dataType: double
		lineageTag: 495da32b-35ee-47a6-b147-6de1bf1092ce
		summarizeBy: sum
		sourceColumn: caught_at_risk_per_1000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column selected_operating_point
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0b2c2361-4a0a-44dc-ab0c-c7f79c241f12
		summarizeBy: none
		sourceColumn: selected_operating_point

		annotation SummarizationSetBy = Automatic

	column target_recall_met
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 333c239f-c1c6-413b-880f-d6427bde9dd2
		summarizeBy: none
		sourceColumn: target_recall_met

		annotation SummarizationSetBy = Automatic

	partition threshold_cost_benefit = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("\\Mac\Home\Desktop\Minh\Tài liệu học tập (DSEB)\Kì 6\KHDL trong Mkt\Final Project\data\processed\threshold_cost_benefit.csv"),[Delimiter=",", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"threshold", type number}, {"accuracy", type number}, {"precision", type number}, {"recall", type number}, {"f1", type number}, {"f2", type number}, {"roc_auc", type number}, {"pr_auc", type number}, {"brier_score", type number}, {"tn", Int64.Type}, {"fp", Int64.Type}, {"fn", Int64.Type}, {"tp", Int64.Type}, {"horizon_day", Int64.Type}, {"model", type text}, {"total_flagged", Int64.Type}, {"flagged_pct", type number}, {"false_alert_ratio", type number}, {"missed_at_risk", Int64.Type}, {"expected_review_load_per_1000", type number}, {"caught_at_risk_per_1000", type number}, {"selected_operating_point", type logical}, {"target_recall_met", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

